#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v4
# autospec commit: 3d985eb
#
Name     : perl-HTML-Tagset
Version  : 3.24
Release  : 51
URL      : https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/HTML-Tagset-3.24.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/HTML-Tagset-3.24.tar.gz
Summary  : 'Data tables useful in parsing HTML'
Group    : Development/Tools
License  : Artistic-1.0-Perl Artistic-2.0
Requires: perl-HTML-Tagset-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# HTML::Tagset
This module contains data tables useful in dealing with HTML.
It provides no functions or methods.

%package dev
Summary: dev components for the perl-HTML-Tagset package.
Group: Development
Provides: perl-HTML-Tagset-devel = %{version}-%{release}
Requires: perl-HTML-Tagset = %{version}-%{release}

%description dev
dev components for the perl-HTML-Tagset package.


%package perl
Summary: perl components for the perl-HTML-Tagset package.
Group: Default
Requires: perl-HTML-Tagset = %{version}-%{release}

%description perl
perl components for the perl-HTML-Tagset package.


%prep
%setup -q -n HTML-Tagset-3.24
cd %{_builddir}/HTML-Tagset-3.24
pushd ..
cp -a HTML-Tagset-3.24 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/HTML::Tagset.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
